import "package:get/get.dart";

class TranslateMessages extends Translations {
  @override
  Map<String,Map<String,String>> get keys => {
    "zh_CN":{
      "body":"正文",
      "Settings":"设置",
      "Back":"返回",
      "Administrator":"管理员",
      "Dashboard":"控制台",
      "Devices":"终端设备",
      "Customers":"客户",
      "Configuration":"配置",
      "Exit":"退出登陆",
      "Display Setting":"显示配置",
      "Dark Model":"暗色模式",
      "Light Model":"亮色模式",
      "Language Setting":"语言设定",
      "Chinese":"中文",
      "English":"英语",
      "Sign In":"登陆",
      "Register New Device":"注册新终端",
      "Terminal Serial No.":"设备终端号",
      "Serial ID could not be empty":"设备终端号不可为空",
      "Model ID":"终端编号",
      "Device Model":"设备型号",
      "Operation System":"操作系统",
      "OS Version":"系统版本",
      "Storage":"存储",
      "RAM":"内存",
      "CPU":"芯片架构",
      "Register Terminal":"新增终端",
      "Terminal Type could not be null":"终端型号不可为空",
      "New Model":"新增型号",
      "Device Model Type could not be empty":"设备型号不可为空",
      "Cancel":"取消",
      "Search":"搜索",
      "Terminal Name":"终端名",
      "Status":"状态",
      "Actions":"操作",
      "Delete":"删除",
      "Edit":"编辑",
      "Remove Terminal Model?":"删除终端型号",
      "Update Terminal Model":"更新终端型号",
      "Confirm to remove this terminal model":"确认删除",
      "Confirm":"确认",
      "Update":"更新",
      "Remove terminal":"删除硬件",
      "Before remove this terminal make sure remove it from IOT core,are you sure?":"确保已在物联网控制台中移除终端",
      "are you sure?":"确认操作",
      "Disable terminal":"停用设备",
      "Enable terminal":"启用设备",
      "Detail":"详情",
      "Enable":"启用",
      "Disable":"禁用",
      "Activate Code":"激活码",
      "Kimacloud Terminal Platform": "旷云商显后台管理平台",

      "Name or Location":"设备名或位置",
    },
    "de_DE":{
      "body": 'Hwllo Welt',
      "Settings":"xxw",
      "Back":"fas",
    },
  };
}